// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: AgencyProtocol.proto

package agency

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//------------------------------------------------------------------------------
// AgencyService 對 microservice 方的通訊
type AgencyToMicro int32

const (
	AgencyToMicro_A2M_NULL                 AgencyToMicro = 0
	AgencyToMicro_A2M_USER_LOGIN           AgencyToMicro = 1
	AgencyToMicro_A2M_USER_LOGOUT          AgencyToMicro = 2
	AgencyToMicro_A2M_GAME_SERVER_LAUNCH   AgencyToMicro = 3
	AgencyToMicro_A2M_GAME_SERVER_SHUTDOWN AgencyToMicro = 4
	AgencyToMicro_A2M_USER_JOIN_GAME       AgencyToMicro = 5
	AgencyToMicro_A2M_USER_LEAVE_GAME      AgencyToMicro = 6
	AgencyToMicro_A2M_USER_UPDATE_STATUS   AgencyToMicro = 7
	AgencyToMicro_A2M_USER_UPDATE_PROFILE  AgencyToMicro = 8
	AgencyToMicro_A2M_GET_MONEY_ACK        AgencyToMicro = 9
)

var AgencyToMicro_name = map[int32]string{
	0: "A2M_NULL",
	1: "A2M_USER_LOGIN",
	2: "A2M_USER_LOGOUT",
	3: "A2M_GAME_SERVER_LAUNCH",
	4: "A2M_GAME_SERVER_SHUTDOWN",
	5: "A2M_USER_JOIN_GAME",
	6: "A2M_USER_LEAVE_GAME",
	7: "A2M_USER_UPDATE_STATUS",
	8: "A2M_USER_UPDATE_PROFILE",
	9: "A2M_GET_MONEY_ACK",
}

var AgencyToMicro_value = map[string]int32{
	"A2M_NULL":                 0,
	"A2M_USER_LOGIN":           1,
	"A2M_USER_LOGOUT":          2,
	"A2M_GAME_SERVER_LAUNCH":   3,
	"A2M_GAME_SERVER_SHUTDOWN": 4,
	"A2M_USER_JOIN_GAME":       5,
	"A2M_USER_LEAVE_GAME":      6,
	"A2M_USER_UPDATE_STATUS":   7,
	"A2M_USER_UPDATE_PROFILE":  8,
	"A2M_GET_MONEY_ACK":        9,
}

func (x AgencyToMicro) String() string {
	return proto.EnumName(AgencyToMicro_name, int32(x))
}

func (AgencyToMicro) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{0}
}

//------------------------------------------------------------------------------
// microservice 對 AgencyService 方的通訊
type MicroToAgency int32

const (
	MicroToAgency_M2A_NULL          MicroToAgency = 0
	MicroToAgency_M2A_GET_MONEY_REQ MicroToAgency = 1
)

var MicroToAgency_name = map[int32]string{
	0: "M2A_NULL",
	1: "M2A_GET_MONEY_REQ",
}

var MicroToAgency_value = map[string]int32{
	"M2A_NULL":          0,
	"M2A_GET_MONEY_REQ": 1,
}

func (x MicroToAgency) String() string {
	return proto.EnumName(MicroToAgency_name, int32(x))
}

func (MicroToAgency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{1}
}

//	更新金錢狀態
type CurrencyChangeStatus int32

const (
	CurrencyChangeStatus_None        CurrencyChangeStatus = 0
	CurrencyChangeStatus_Success     CurrencyChangeStatus = 1
	CurrencyChangeStatus_NoUser      CurrencyChangeStatus = 2
	CurrencyChangeStatus_OutOfMoney  CurrencyChangeStatus = 3
	CurrencyChangeStatus_SystemError CurrencyChangeStatus = 4
)

var CurrencyChangeStatus_name = map[int32]string{
	0: "None",
	1: "Success",
	2: "NoUser",
	3: "OutOfMoney",
	4: "SystemError",
}

var CurrencyChangeStatus_value = map[string]int32{
	"None":        0,
	"Success":     1,
	"NoUser":      2,
	"OutOfMoney":  3,
	"SystemError": 4,
}

func (x CurrencyChangeStatus) String() string {
	return proto.EnumName(CurrencyChangeStatus_name, int32(x))
}

func (CurrencyChangeStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{2}
}

type UserProfile struct {
	LoginId              string   `protobuf:"bytes,1,opt,name=loginId,proto3" json:"loginId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AccountId            uint32   `protobuf:"varint,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CountryCode          string   `protobuf:"bytes,4,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Language             int32    `protobuf:"varint,5,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{0}
}
func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *UserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserProfile) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *UserProfile) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *UserProfile) GetLanguage() int32 {
	if m != nil {
		return m.Language
	}
	return 0
}

type UserStatus struct {
	DepositTimes         uint32   `protobuf:"varint,1,opt,name=depositTimes,proto3" json:"depositTimes,omitempty"`
	DepositAmount        float64  `protobuf:"fixed64,2,opt,name=depositAmount,proto3" json:"depositAmount,omitempty"`
	VipLevel             int32    `protobuf:"varint,3,opt,name=vipLevel,proto3" json:"vipLevel,omitempty"`
	PreVipLevel          int32    `protobuf:"varint,4,opt,name=preVipLevel,proto3" json:"preVipLevel,omitempty"`
	MonthlyPass          int64    `protobuf:"varint,5,opt,name=monthlyPass,proto3" json:"monthlyPass,omitempty"`
	TotalAmount          float64  `protobuf:"fixed64,6,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	LastMonthAmount      float64  `protobuf:"fixed64,7,opt,name=lastMonthAmount,proto3" json:"lastMonthAmount,omitempty"`
	CurMonthAmount       float64  `protobuf:"fixed64,8,opt,name=curMonthAmount,proto3" json:"curMonthAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStatus) Reset()         { *m = UserStatus{} }
func (m *UserStatus) String() string { return proto.CompactTextString(m) }
func (*UserStatus) ProtoMessage()    {}
func (*UserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{1}
}
func (m *UserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStatus.Unmarshal(m, b)
}
func (m *UserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStatus.Marshal(b, m, deterministic)
}
func (m *UserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStatus.Merge(m, src)
}
func (m *UserStatus) XXX_Size() int {
	return xxx_messageInfo_UserStatus.Size(m)
}
func (m *UserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UserStatus proto.InternalMessageInfo

func (m *UserStatus) GetDepositTimes() uint32 {
	if m != nil {
		return m.DepositTimes
	}
	return 0
}

func (m *UserStatus) GetDepositAmount() float64 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

func (m *UserStatus) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *UserStatus) GetPreVipLevel() int32 {
	if m != nil {
		return m.PreVipLevel
	}
	return 0
}

func (m *UserStatus) GetMonthlyPass() int64 {
	if m != nil {
		return m.MonthlyPass
	}
	return 0
}

func (m *UserStatus) GetTotalAmount() float64 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *UserStatus) GetLastMonthAmount() float64 {
	if m != nil {
		return m.LastMonthAmount
	}
	return 0
}

func (m *UserStatus) GetCurMonthAmount() float64 {
	if m != nil {
		return m.CurMonthAmount
	}
	return 0
}

type UserLoginData struct {
	Profile              *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Status               *UserStatus  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserLoginData) Reset()         { *m = UserLoginData{} }
func (m *UserLoginData) String() string { return proto.CompactTextString(m) }
func (*UserLoginData) ProtoMessage()    {}
func (*UserLoginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{2}
}
func (m *UserLoginData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginData.Unmarshal(m, b)
}
func (m *UserLoginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginData.Marshal(b, m, deterministic)
}
func (m *UserLoginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginData.Merge(m, src)
}
func (m *UserLoginData) XXX_Size() int {
	return xxx_messageInfo_UserLoginData.Size(m)
}
func (m *UserLoginData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginData.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginData proto.InternalMessageInfo

func (m *UserLoginData) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *UserLoginData) GetStatus() *UserStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type UserAccountData struct {
	AccountId            uint32   `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAccountData) Reset()         { *m = UserAccountData{} }
func (m *UserAccountData) String() string { return proto.CompactTextString(m) }
func (*UserAccountData) ProtoMessage()    {}
func (*UserAccountData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{3}
}
func (m *UserAccountData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountData.Unmarshal(m, b)
}
func (m *UserAccountData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountData.Marshal(b, m, deterministic)
}
func (m *UserAccountData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountData.Merge(m, src)
}
func (m *UserAccountData) XXX_Size() int {
	return xxx_messageInfo_UserAccountData.Size(m)
}
func (m *UserAccountData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountData.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountData proto.InternalMessageInfo

func (m *UserAccountData) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GameServerData struct {
	ThemeId              uint32   `protobuf:"varint,1,opt,name=themeId,proto3" json:"themeId,omitempty"`
	GameId               uint32   `protobuf:"varint,2,opt,name=gameId,proto3" json:"gameId,omitempty"`
	ThemeName            string   `protobuf:"bytes,3,opt,name=themeName,proto3" json:"themeName,omitempty"`
	GameName             string   `protobuf:"bytes,4,opt,name=gameName,proto3" json:"gameName,omitempty"`
	GroupName            string   `protobuf:"bytes,5,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerData) Reset()         { *m = GameServerData{} }
func (m *GameServerData) String() string { return proto.CompactTextString(m) }
func (*GameServerData) ProtoMessage()    {}
func (*GameServerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{4}
}
func (m *GameServerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerData.Unmarshal(m, b)
}
func (m *GameServerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerData.Marshal(b, m, deterministic)
}
func (m *GameServerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerData.Merge(m, src)
}
func (m *GameServerData) XXX_Size() int {
	return xxx_messageInfo_GameServerData.Size(m)
}
func (m *GameServerData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerData.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerData proto.InternalMessageInfo

func (m *GameServerData) GetThemeId() uint32 {
	if m != nil {
		return m.ThemeId
	}
	return 0
}

func (m *GameServerData) GetGameId() uint32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GameServerData) GetThemeName() string {
	if m != nil {
		return m.ThemeName
	}
	return ""
}

func (m *GameServerData) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *GameServerData) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type GameServerNotifyData struct {
	ThemeId              uint32   `protobuf:"varint,1,opt,name=themeId,proto3" json:"themeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerNotifyData) Reset()         { *m = GameServerNotifyData{} }
func (m *GameServerNotifyData) String() string { return proto.CompactTextString(m) }
func (*GameServerNotifyData) ProtoMessage()    {}
func (*GameServerNotifyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{5}
}
func (m *GameServerNotifyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerNotifyData.Unmarshal(m, b)
}
func (m *GameServerNotifyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerNotifyData.Marshal(b, m, deterministic)
}
func (m *GameServerNotifyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerNotifyData.Merge(m, src)
}
func (m *GameServerNotifyData) XXX_Size() int {
	return xxx_messageInfo_GameServerNotifyData.Size(m)
}
func (m *GameServerNotifyData) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerNotifyData.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerNotifyData proto.InternalMessageInfo

func (m *GameServerNotifyData) GetThemeId() uint32 {
	if m != nil {
		return m.ThemeId
	}
	return 0
}

type UserJoinLeaveGameData struct {
	ThemeId              uint32   `protobuf:"varint,1,opt,name=themeId,proto3" json:"themeId,omitempty"`
	AccountId            uint32   `protobuf:"varint,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserJoinLeaveGameData) Reset()         { *m = UserJoinLeaveGameData{} }
func (m *UserJoinLeaveGameData) String() string { return proto.CompactTextString(m) }
func (*UserJoinLeaveGameData) ProtoMessage()    {}
func (*UserJoinLeaveGameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{6}
}
func (m *UserJoinLeaveGameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserJoinLeaveGameData.Unmarshal(m, b)
}
func (m *UserJoinLeaveGameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserJoinLeaveGameData.Marshal(b, m, deterministic)
}
func (m *UserJoinLeaveGameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserJoinLeaveGameData.Merge(m, src)
}
func (m *UserJoinLeaveGameData) XXX_Size() int {
	return xxx_messageInfo_UserJoinLeaveGameData.Size(m)
}
func (m *UserJoinLeaveGameData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserJoinLeaveGameData.DiscardUnknown(m)
}

var xxx_messageInfo_UserJoinLeaveGameData proto.InternalMessageInfo

func (m *UserJoinLeaveGameData) GetThemeId() uint32 {
	if m != nil {
		return m.ThemeId
	}
	return 0
}

func (m *UserJoinLeaveGameData) GetAccountId() uint32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type Money struct {
	CreditIn             int64    `protobuf:"varint,1,opt,name=creditIn,proto3" json:"creditIn,omitempty"`
	WinIn                int64    `protobuf:"varint,2,opt,name=winIn,proto3" json:"winIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Money) Reset()         { *m = Money{} }
func (m *Money) String() string { return proto.CompactTextString(m) }
func (*Money) ProtoMessage()    {}
func (*Money) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{7}
}
func (m *Money) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Money.Unmarshal(m, b)
}
func (m *Money) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Money.Marshal(b, m, deterministic)
}
func (m *Money) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Money.Merge(m, src)
}
func (m *Money) XXX_Size() int {
	return xxx_messageInfo_Money.Size(m)
}
func (m *Money) XXX_DiscardUnknown() {
	xxx_messageInfo_Money.DiscardUnknown(m)
}

var xxx_messageInfo_Money proto.InternalMessageInfo

func (m *Money) GetCreditIn() int64 {
	if m != nil {
		return m.CreditIn
	}
	return 0
}

func (m *Money) GetWinIn() int64 {
	if m != nil {
		return m.WinIn
	}
	return 0
}

type UserMoney struct {
	Property             []*Money `protobuf:"bytes,1,rep,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMoney) Reset()         { *m = UserMoney{} }
func (m *UserMoney) String() string { return proto.CompactTextString(m) }
func (*UserMoney) ProtoMessage()    {}
func (*UserMoney) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{8}
}
func (m *UserMoney) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMoney.Unmarshal(m, b)
}
func (m *UserMoney) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMoney.Marshal(b, m, deterministic)
}
func (m *UserMoney) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMoney.Merge(m, src)
}
func (m *UserMoney) XXX_Size() int {
	return xxx_messageInfo_UserMoney.Size(m)
}
func (m *UserMoney) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMoney.DiscardUnknown(m)
}

var xxx_messageInfo_UserMoney proto.InternalMessageInfo

func (m *UserMoney) GetProperty() []*Money {
	if m != nil {
		return m.Property
	}
	return nil
}

type GetMoneyAckData struct {
	Res                  CurrencyChangeStatus `protobuf:"varint,1,opt,name=res,proto3,enum=agency.CurrencyChangeStatus" json:"res,omitempty"`
	Money                *UserMoney           `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetMoneyAckData) Reset()         { *m = GetMoneyAckData{} }
func (m *GetMoneyAckData) String() string { return proto.CompactTextString(m) }
func (*GetMoneyAckData) ProtoMessage()    {}
func (*GetMoneyAckData) Descriptor() ([]byte, []int) {
	return fileDescriptor_190592c454e29f61, []int{9}
}
func (m *GetMoneyAckData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoneyAckData.Unmarshal(m, b)
}
func (m *GetMoneyAckData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoneyAckData.Marshal(b, m, deterministic)
}
func (m *GetMoneyAckData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoneyAckData.Merge(m, src)
}
func (m *GetMoneyAckData) XXX_Size() int {
	return xxx_messageInfo_GetMoneyAckData.Size(m)
}
func (m *GetMoneyAckData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoneyAckData.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoneyAckData proto.InternalMessageInfo

func (m *GetMoneyAckData) GetRes() CurrencyChangeStatus {
	if m != nil {
		return m.Res
	}
	return CurrencyChangeStatus_None
}

func (m *GetMoneyAckData) GetMoney() *UserMoney {
	if m != nil {
		return m.Money
	}
	return nil
}

func init() {
	proto.RegisterEnum("agency.AgencyToMicro", AgencyToMicro_name, AgencyToMicro_value)
	proto.RegisterEnum("agency.MicroToAgency", MicroToAgency_name, MicroToAgency_value)
	proto.RegisterEnum("agency.CurrencyChangeStatus", CurrencyChangeStatus_name, CurrencyChangeStatus_value)
	proto.RegisterType((*UserProfile)(nil), "agency.UserProfile")
	proto.RegisterType((*UserStatus)(nil), "agency.UserStatus")
	proto.RegisterType((*UserLoginData)(nil), "agency.UserLoginData")
	proto.RegisterType((*UserAccountData)(nil), "agency.UserAccountData")
	proto.RegisterType((*GameServerData)(nil), "agency.GameServerData")
	proto.RegisterType((*GameServerNotifyData)(nil), "agency.GameServerNotifyData")
	proto.RegisterType((*UserJoinLeaveGameData)(nil), "agency.UserJoinLeaveGameData")
	proto.RegisterType((*Money)(nil), "agency.Money")
	proto.RegisterType((*UserMoney)(nil), "agency.UserMoney")
	proto.RegisterType((*GetMoneyAckData)(nil), "agency.GetMoneyAckData")
}

func init() { proto.RegisterFile("AgencyProtocol.proto", fileDescriptor_190592c454e29f61) }

var fileDescriptor_190592c454e29f61 = []byte{
	// 818 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x4d, 0x8f, 0xe3, 0x44,
	0x10, 0x5d, 0xc7, 0xf9, 0x9a, 0xca, 0x26, 0xf1, 0xf4, 0x7c, 0xac, 0xb5, 0xcc, 0x21, 0xb2, 0x10,
	0x84, 0x91, 0x18, 0x50, 0x40, 0x48, 0x1c, 0x4d, 0xc6, 0xcc, 0x64, 0x49, 0xec, 0xd0, 0x76, 0x06,
	0xc1, 0x25, 0x32, 0x4e, 0x4f, 0xc6, 0xbb, 0x89, 0x3b, 0x6a, 0x77, 0x06, 0xe5, 0xc8, 0xdf, 0xe0,
	0xc2, 0x9d, 0x5f, 0x89, 0xba, 0x1c, 0x3b, 0x9e, 0x08, 0xb1, 0xb7, 0xae, 0xf7, 0x5e, 0x75, 0xbd,
	0xae, 0xaa, 0xc4, 0x70, 0x6e, 0x2f, 0x59, 0x12, 0xed, 0xa6, 0x82, 0x4b, 0x1e, 0xf1, 0xd5, 0xcd,
	0x46, 0x1d, 0x48, 0x3d, 0x44, 0xd4, 0xfa, 0x5b, 0x83, 0xd6, 0x2c, 0x65, 0x62, 0x2a, 0xf8, 0x63,
	0xbc, 0x62, 0xc4, 0x84, 0xc6, 0x8a, 0x2f, 0xe3, 0x64, 0xb4, 0x30, 0xb5, 0x9e, 0xd6, 0x3f, 0xa1,
	0x79, 0x48, 0xde, 0x42, 0x33, 0x89, 0xa3, 0x0f, 0x49, 0xb8, 0x66, 0x66, 0x05, 0xa9, 0x22, 0x26,
	0x57, 0x70, 0x12, 0x46, 0x11, 0xdf, 0x26, 0x72, 0xb4, 0x30, 0xf5, 0x9e, 0xd6, 0x6f, 0xd3, 0x03,
	0x40, 0x7a, 0xd0, 0xc2, 0xa3, 0xd8, 0x0d, 0xf9, 0x82, 0x99, 0x55, 0x4c, 0x2e, 0x43, 0xea, 0xee,
	0x55, 0x98, 0x2c, 0xb7, 0xe1, 0x92, 0x99, 0xb5, 0x9e, 0xd6, 0xaf, 0xd1, 0x22, 0xb6, 0xfe, 0xa9,
	0x00, 0x28, 0x87, 0xbe, 0x0c, 0xe5, 0x36, 0x25, 0x16, 0xbc, 0x5e, 0xb0, 0x0d, 0x4f, 0x63, 0x19,
	0xc4, 0x6b, 0x96, 0xa2, 0xcb, 0x36, 0x7d, 0x81, 0x91, 0x4f, 0xa1, 0xbd, 0x8f, 0xed, 0xb5, 0xaa,
	0x82, 0x7e, 0x35, 0xfa, 0x12, 0x54, 0x45, 0x9f, 0xe3, 0xcd, 0x98, 0x3d, 0xb3, 0x15, 0x7a, 0xae,
	0xd1, 0x22, 0x56, 0x96, 0x37, 0x82, 0x3d, 0xe4, 0x74, 0x15, 0xe9, 0x32, 0xa4, 0x14, 0x6b, 0x9e,
	0xc8, 0xa7, 0xd5, 0x6e, 0x1a, 0xa6, 0x29, 0xba, 0xd6, 0x69, 0x19, 0x52, 0x0a, 0xc9, 0x65, 0xb8,
	0xda, 0x7b, 0xa8, 0xa3, 0x87, 0x32, 0x44, 0xfa, 0xd0, 0x5d, 0x85, 0xa9, 0x9c, 0xa8, 0xa4, 0xbd,
	0xaa, 0x81, 0xaa, 0x63, 0x98, 0x7c, 0x06, 0x9d, 0x68, 0x2b, 0xca, 0xc2, 0x26, 0x0a, 0x8f, 0x50,
	0xeb, 0x3d, 0xb4, 0x55, 0xaf, 0xc6, 0x6a, 0x66, 0xb7, 0xa1, 0x0c, 0xc9, 0x97, 0xd0, 0xd8, 0x64,
	0xa3, 0xc5, 0x4e, 0xb5, 0x06, 0x67, 0x37, 0xd9, 0xe4, 0x6f, 0x4a, 0x53, 0xa7, 0xb9, 0x86, 0x5c,
	0x43, 0x3d, 0xc5, 0x3e, 0x63, 0xcb, 0x5a, 0x03, 0x52, 0x56, 0x67, 0x13, 0xa0, 0x7b, 0x85, 0xf5,
	0x15, 0x74, 0x15, 0x6a, 0x67, 0x73, 0xc6, 0x6a, 0x2f, 0xf6, 0x40, 0x3b, 0xda, 0x03, 0xeb, 0x2f,
	0x0d, 0x3a, 0x77, 0xe1, 0x9a, 0xf9, 0x4c, 0x3c, 0x33, 0x81, 0x09, 0x26, 0x34, 0xe4, 0x13, 0x5b,
	0xb3, 0x42, 0x9e, 0x87, 0xe4, 0x12, 0xea, 0xcb, 0x10, 0x89, 0x0a, 0x12, 0xfb, 0x48, 0x95, 0x40,
	0x89, 0xab, 0xf6, 0x50, 0xc7, 0x55, 0x3a, 0x00, 0x6a, 0xa6, 0x4a, 0x87, 0x64, 0xb6, 0x67, 0x45,
	0xac, 0x32, 0x97, 0x82, 0x6f, 0x37, 0x48, 0xd6, 0xb2, 0xcc, 0x02, 0xb0, 0xbe, 0x86, 0xf3, 0x83,
	0x37, 0x97, 0xcb, 0xf8, 0x71, 0xf7, 0xff, 0x0e, 0x2d, 0x0f, 0x2e, 0xd4, 0xfb, 0xdf, 0xf1, 0x38,
	0x19, 0xb3, 0xf0, 0x99, 0xa9, 0xf4, 0x8f, 0x3c, 0xea, 0x45, 0x7f, 0x2a, 0xc7, 0xfd, 0xf9, 0x1e,
	0x6a, 0x13, 0x9e, 0xb0, 0x9d, 0x7a, 0x45, 0x24, 0xd8, 0x22, 0x96, 0xa3, 0x04, 0x6f, 0xd0, 0x69,
	0x11, 0x93, 0x73, 0xa8, 0xfd, 0x11, 0x27, 0xa3, 0x04, 0xd3, 0x75, 0x9a, 0x05, 0xd6, 0x77, 0x70,
	0xa2, 0xbc, 0x64, 0xe9, 0x5f, 0x40, 0x73, 0x23, 0xf8, 0x86, 0x09, 0xb9, 0x33, 0xb5, 0x9e, 0xde,
	0x6f, 0x0d, 0xda, 0xf9, 0x18, 0x51, 0x40, 0x0b, 0xda, 0x7a, 0x0f, 0xdd, 0x3b, 0x26, 0x11, 0xb5,
	0xa3, 0x0f, 0xe8, 0xfe, 0x06, 0x74, 0xb1, 0xff, 0x5d, 0x75, 0x06, 0x57, 0x79, 0xe2, 0x70, 0x2b,
	0x84, 0x3a, 0x0c, 0x9f, 0xc2, 0x64, 0xc9, 0xf6, 0x9b, 0xa0, 0x84, 0xe4, 0x73, 0xa8, 0xad, 0x55,
	0xfe, 0x7e, 0x63, 0x4e, 0xcb, 0x1b, 0x93, 0x95, 0xcb, 0xf8, 0xeb, 0x3f, 0x2b, 0xd0, 0xce, 0xfe,
	0x8b, 0x02, 0x3e, 0x89, 0x23, 0xc1, 0xc9, 0x6b, 0x68, 0xda, 0x83, 0xc9, 0xdc, 0x9d, 0x8d, 0xc7,
	0xc6, 0x2b, 0x42, 0xa0, 0xa3, 0xa2, 0x99, 0xef, 0xd0, 0xf9, 0xd8, 0xbb, 0x1b, 0xb9, 0x86, 0x46,
	0xce, 0xa0, 0x5b, 0xc6, 0xbc, 0x59, 0x60, 0x54, 0xc8, 0x5b, 0xb8, 0x54, 0xe0, 0x9d, 0x3d, 0x71,
	0xe6, 0xbe, 0x43, 0x1f, 0x14, 0x67, 0xcf, 0xdc, 0xe1, 0xbd, 0xa1, 0x93, 0x2b, 0x30, 0x8f, 0x39,
	0xff, 0x7e, 0x16, 0xdc, 0x7a, 0xbf, 0xb8, 0x46, 0x95, 0x5c, 0x02, 0x29, 0xae, 0x7b, 0xe7, 0x8d,
	0x5c, 0xd4, 0x19, 0x35, 0xf2, 0x06, 0xce, 0x0e, 0x65, 0x1c, 0xfb, 0xc1, 0xc9, 0x88, 0x7a, 0x5e,
	0x0a, 0x89, 0xd9, 0xf4, 0xd6, 0x0e, 0x9c, 0xb9, 0x1f, 0xd8, 0xc1, 0xcc, 0x37, 0x1a, 0xe4, 0x13,
	0x78, 0x73, 0xcc, 0x4d, 0xa9, 0xf7, 0xe3, 0x68, 0xec, 0x18, 0x4d, 0x72, 0x01, 0xa7, 0xe8, 0xc3,
	0x09, 0xe6, 0x13, 0xcf, 0x75, 0x7e, 0x9d, 0xdb, 0xc3, 0x9f, 0x8c, 0x93, 0xeb, 0x6f, 0xa1, 0x8d,
	0x4f, 0x0f, 0x78, 0xd6, 0x09, 0xd5, 0x82, 0xc9, 0xc0, 0xce, 0x5b, 0x70, 0x01, 0xa7, 0x2a, 0x3a,
	0x64, 0x51, 0xe7, 0x67, 0x43, 0xbb, 0xfe, 0x0d, 0xce, 0xff, 0xab, 0xff, 0xa4, 0x09, 0x55, 0x97,
	0x27, 0xcc, 0x78, 0x45, 0x5a, 0xd0, 0xf0, 0xb7, 0x51, 0xc4, 0xd2, 0xd4, 0xd0, 0x08, 0x40, 0xdd,
	0xe5, 0xaa, 0xfd, 0x46, 0x85, 0x74, 0x00, 0xbc, 0xad, 0xf4, 0x1e, 0x71, 0x12, 0x86, 0x4e, 0xba,
	0xd0, 0xf2, 0x77, 0xa9, 0x64, 0x6b, 0x47, 0x08, 0x2e, 0x8c, 0xea, 0x0f, 0x95, 0x7b, 0xed, 0xf7,
	0x3a, 0x7e, 0x13, 0xbe, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xa7, 0x2d, 0xf8, 0x2b, 0x06,
	0x00, 0x00,
}
